### DISCUSSION TITLE
Termux support on Android

### DISCUSSION THREAD

**Discussion by rahaaatul** [mar10/wsgidav#322] [Q&A]
Can we install and run on termux on android? If yes, how? If no, is there a possibility to add support for Android too?

**Comment by rahaaatul** [comment]
I installed and configured it on termux.

I can access it via Edge Browser. But I cannot do it using Windows explorer and Kodi.

Here's my config file:
```yaml
server: cheroot
host: 192.168.1.101
port: 8080

provider_mapping:
    '/': '/storage/emulated/0'

http_authenticator:
    accept_basic: true

simple_dc:
    user_mapping:
        '*':
            '....':
                password: '....'
                roles: ['admin']

verbose: 2
```

What am I doing wrong? Here's ther error:

![image](https://github.com/user-attachments/assets/bfbf5d23-722e-4923-ba77-97755ca0f2ed)
