### ISSUE TITLE
give user their own subfolder

### ISSUE THREAD

**Issue by MrMoronIV** [mar10/wsgidav#107]
Is it possible to give a user their own folder?
At the moment I need to define a realm, which is a subfolder and add a user to it. But any user added to this realm (subfolder) has access to the same files.

I would like to have one realm: / so there is no need to use a subfolder when logging in and lock the user to their own internal subfolder which they don't know about, so something like this:
```
provider_mapping:
    "/": "/webdav"

user_mapping:
    "/":
        "bob":
            password: "bob"
            description: ""
            path: "/bob"
            roles: []
```
which would internally result in `/webdav/bob` although client software just shows `/`
The reason is that I want to give every user their own space but I want them to use the main domain (storage.example.com) to connect instead of storage.example.com/bob
Especially since I'm using a non-standard port it can get confusing to setup the address correctly in some client software programs if the 'realm' is required.

subquestion: what are roles used for? Can't find anything in the docs about it.
