### ISSUE TITLE
Encrypted passwords and support for htpasswd

### ISSUE THREAD

**Issue by MrMoronIV** [mar10/wsgidav#108]
I'm just posting the questions I run into while setting up wsgidav, hope that's ok.

Is is possible to put encrypted passwords in the conf file instead of plain text? this for obvious reasons.

Better yet, is it possible to use a `htpasswd` file and if so, how?
It would be nice if you could define something like:
```
http_authenticator:
    accept_basic: false    # Allow basic authentication
    accept_digest: true    # Allow digest authentication
    default_to_digest: true   # true (default digest) or false (default basic)
    trusted_auth_header: null
    htpasswd: /path/to/.htpasswd
```
