### ISSUE TITLE
How to have a backend plugin

### ISSUE THREAD

**Issue by vanrein** [mar10/wsgidav#176]
I made a [reasonable first version](https://github.com/mar10/wsgidav/compare/master...arpa2:arpa2reservoir) of a backend plugin.  It uses our idea of an object store, with metadata in LDAP.  WebDAV and LDAP are surprisingly similar, so the relation could be quite beneficial.

Would you like such a backend integrated into the wsgidav distribution via a Pull Request, or would you prefer it distributed separately?  In the latter case, please explain your ideas on backend API and versioning -- for instance, should we call it our `wsgidav3` plugin and then rely on its compatibility with wsgidev 3.y.z versions from 3.0.3 onward?

Configuration is not completely clear, and your otherwise excellent documentation does not really help (or I missed it).  Currently, I'm suggesting a [modification to wsgidav_app.py](https://github.com/mar10/wsgidav/compare/master...arpa2:arpa2reservoir#diff-7868c9b71c5c36c21765a2f20bd2a4b1) which I'm pretty sure you'd like to suppress where possible; what would you suggest?  (FWIW, the `ldapuri` is now also available in a configuration file, but `apphint` is still needed because it may vary between prefixes.)

If I wasn't clear yet -- I think `wsgidav` is a really nice piece of code, and it was pleasant to link it to our backend structures without knowing all intricacies of WebDAV.  As far as I'm concerned, your plugin API works.

**Comment by mar10** [comment]
Hi,
first off, thanks for taking the time to contribute: These kind of extensions are much appreciated.

As you assumed, I would generally like to avoid modifying core code to add specific extensions, but if we can enhance the integration API or documentation I am open to it. I will look into it during the next days.

**Comment by vanrein** [comment]
Hi,

> As you assumed, I would generally like to avoid modifying core code to add specific extensions, but if we can enhance the integration API or documentation I am open to it. I will look into it during the next days.

Without changes, I suppose you are looking for something like (pardon my YAML)

```
provider_mapping:
  "/":
     provider: wsgidav.arpa2reservoir_provider.ARPA2ReservoirProvider
     kwargs:
        ldapuri: xxx
        homedir: /var/arpa2/reservoir
        apphint: Music
        readonly: False
```

If this is correct, then the extra indirection with `kwargs` feels superfluous, and may be confusing to plugin users.  Have you considered passing on as `kwargs` any key that you didn't recognise (or perhaps all)?  I suppose that would change it to a more logical form,


```
provider_mapping:
  "/":
     provider: wsgidav.arpa2reservoir_provider.ARPA2ReservoirProvider
     ldapuri: xxx
     homedir: /var/arpa2/reservoir
     apphint: Music
     readonly: False
```

**Comment by mar10** [comment]
Currently providers can be declared like 

```yaml
"/":
  provider: PATH.TO.PROVIDER
    args:
      - pos_arg_1
      - pos_arg_2
    kwargs:
      named_arg_1: nv_1
      named_arg_2: nv_2
```
(See `WsgiDAVApp.add_provider()`)
Would this work in your case?

We *may* add your code sample to [the demos](https://github.com/mar10/wsgidav/tree/master/wsgidav/samples) and [documentation](https://wsgidav.readthedocs.io/en/latest/user_guide_custom_providers.html), but it may be easier if you host it at your site (and if you like add a link to our docs). This would also clarify copyright issues.

The version scheme should roughly follow [semver](https://semver.org).
