### ISSUE TITLE
favicon should be on root

### ISSUE THREAD

**Issue by pvgenuchten** [mar10/wsgidav#230]
browsers look for favicon.ico at root of a website when opening a non html file, however in dir-browser it is placed in /:dir_browser/favion.ico
this results in empty favicon for non html resources and a 404 error on the logs
can the tool introduce a forward rule from /favicon.ico to /:dir_browser/favicon.ico?

workaround is to place favicon.ico also in root webdav folder

**Comment by mar10** [comment]
Could you describe how to reproduce the behavior?

**Comment by pvgenuchten** [comment]
reproduce:

Wrong:
- open dir-browser in browser, place and open a .txt or .xml file in the browser
- notice the blank page icon on the browser tab
- notice a 404 response to /favicon.ico in logs

Correct
- Place a favicon.ico in public / of webdav
- open dir-browser in browser, place and open a .txt or .xml file in the browser
- Notice the icon in browser tab and no 404 response in logs

**Comment by mar10** [comment]
(reproduced on Chrome, Firefox, but not Safari)

**Comment by mar10** [comment]
FWIW: v4.3.0 introduces a new option `fs_dav_provider.shadow_map`
that may be set like so
```yaml
#: Addional configuration passed to `FilesystemProvider(..., fs_opts)`
fs_dav_provider:
    #: Mapping from request URL to physical file location, e.g.
    #: make sure that a `/favicon.ico` URL is resolved, even if a `*.html`
    #: or `*.txt` resource file was opened using the DirBrowser
    shadow_map:
        '/favicon.ico': 'file_path/to/favicon.ico'
```
