### ISSUE TITLE
Cors error

### ISSUE THREAD

**Issue by rusaym** [mar10/wsgidav#273]
**Describe the bug**
I'm trying to connect to my server through the js webdav client [https://www.npmjs.com/package/webdav](https://www.npmjs.com/package/webdav) and got Cors error

![image](https://user-images.githubusercontent.com/17137916/199712343-06247285-18f6-4b35-80b3-06f41f18ce15.png)

Do I have to change something in my config?

**To Reproduce**
1. Start server with default settings 
2. Connect to server:
```
const { createClient } = require("webdav");

const client = createClient(
   "http://localhost:8087/",
    {
        username: "marie",
        password: "myS3curePa$$w0rd"
    }
);
```

**Environment:**
```
WsgiDAV/4.0.2 Python/3.10.6(64 bit) Linux-5.18.0-051800rc1-generic-x86_64-with-glibc2.35
```

**Comment by mar10** [comment]
You could try to enable cors
```yaml
cors:
    #: List of allowed Origins or '*'
    #: Default: false, i.e. prevent CORS
    # allow_origin: null
    allow_origin: '*'
```
See the [sample config](https://github.com/mar10/wsgidav/blob/master/sample_wsgidav.yaml) for details.
